import { environment } from '../../../environments/environment.prod';

const baseUrl = environment.baseUrl;
export const apiMap = {
    addManageSMS: `${baseUrl}/cms/service/AddManageSMS`,
    addUser: `${baseUrl}/user/service/AddUser`,
    addBankAccountDetails: `${baseUrl}/cms/service/AddBankAccountDetails`,
    agentList: `${baseUrl}/user/service/AgentList`,
    agentDetails: `${baseUrl}/user/service/AgentDetails`,
    agentAccoutCredit: `${baseUrl}/transaction/service/AgentAccoutCredit`,
    agentAccoutDebit: `${baseUrl}/transaction/service/AgentAccoutDebit`,
    bankAccountDetails: `${baseUrl}/cms/service/BankAccountDetails`,
    bookingCalender: `${baseUrl}/transaction/service/BookingCalender`,
    bookingDetails: `${baseUrl}/transaction/service/BookingDetails`,
    bookingReports: `${baseUrl}/flight/service/BookingReports`,
    cityList: baseUrl + '/common/service/CityList',
    countryList: `${baseUrl}/common/service/CountryList`,
    currencyConverison: `${baseUrl}/cms/service/CurrencyConverison`,
    editUser: `${baseUrl}/user/service/EditUser`,
    flightVoucher: `${baseUrl}/voucher/service/FlightVoucher`,
    latestMembers: `${baseUrl}/user/service/LatestMembers`,
    latestTransactions: `${baseUrl}/transaction/service/LatestTransactions`,
    loggedInUserList: `${baseUrl}/user/service/LoggedInUserList`,
    manageDomain: `${baseUrl}/cms/service/ManageDomain`,
    manageSMS: `${baseUrl}/cms/service/ManageSMS`,
    moduleBookingCount: `${baseUrl}/transaction/service/ModuleBookingCount`,
    monthlyRecapReport: `${baseUrl}/transaction/service/MonthlyRecapReport`,
    searchHistory: `${baseUrl}/transaction/service/SearchHistory`,
    sEO: `${baseUrl}/cms/service/SEO`,
    socialLogin: `${baseUrl}/cms/service/SocialLogin`,
    socialNetwork: `${baseUrl}/cms/service/SocialNetwork`,
    transactionLogs: `${baseUrl}/transaction/service/TransactionLogs`,
    userList: `${baseUrl}/user/service/UserList`,
    userTitleList: `${baseUrl}/user/service/UserTitleList`,
    userTypeList: `${baseUrl}/user/service/UserTypeList`,
    updateBankAccountDetails: `${baseUrl}/cms/service/UpdateBankAccountDetails`,
    updateCurrencyConverison: `${baseUrl}/cms/service/UpdateCurrencyConverison`,
    updateManageDomain: `${baseUrl}/cms/service/UpdateManageDomain`,
    updateManageSMS: `${baseUrl}/cms/service/UpdateManageSMS`,
    updateSEO: `${baseUrl}/cms/service/UpdateSEO`,
    updateSocialLogin: baseUrl + '/cms/service/UpdateSocialLogin',
    updateSocialNetwork: baseUrl + '/cms/service/UpdateSocialNetwork',
    updateUser: `${baseUrl}/user/service/UpdateUser`,

    userLogin: `${baseUrl}/user/service/UserLogin`,
    editProfile: `${baseUrl}/user/service/EditProfile`,
    updateProfile: `${baseUrl}/user/service/UpdateProfile`,
    userLogout: `${baseUrl}/user/service/UserLogout`,
    changePassword: `${baseUrl}/user/service/ChangePassword`,
    forgotPassword: `${baseUrl}/user/service/UserForgotPassword`,
};